### ISSUE TITLE
Danilo  - Desarrollar Clase Libro

### ISSUE THREAD

**Issue by dannymunozramirez** [dannymunozramirez/AppBiblioteca#4]
Danilo, desarrollar Clase libro con su lógica y atributos

**Comment by dacarrascob** [comment]
public class ValidacionRut {
        private int rut;
        private String rutDigito;
        private int Digito;
        private int Multiplo;
        private int Acumulador;

    public ValidacionRut(String rutDigito, int Digito, int Multiplo, int Acumulador, int rut) {
        this.rutDigito = rutDigito;
        this.Digito = Digito;
        this.Multiplo = Multiplo;
        this.Acumulador = Acumulador;
    }

    public ValidacionRut() {
    }

    public String getRutDigito() {
        return rutDigito;
    }

    public void setRutDigito(String rutDigito) {
        this.rutDigito = rutDigito;
    }

    public int getDigito() {
        return Digito;
    }

    public void setDigito(int Digito) {
        this.Digito = Digito;
    }

    public int getMultiplo() {
        return Multiplo;
    }

    public void setMultiplo(int Multiplo) {
        this.Multiplo = Multiplo;
    }

    public int getAcumulador() {
        return Acumulador;
    }

    public void setAcumulador(int Acumulador) {
        this.Acumulador = Acumulador;
    }
    public int getRut() {
        return rut;
    }
    
    public void setRut(int rut){
        this.rut=rut;
    }
    public void ValidarRut(){
        int contador;
        contador=2;
        Acumulador=0;
        while (rut!=0){
            Multiplo=(rut%10)*contador;
            Acumulador=Acumulador+Multiplo;
            rut=rut/10;
            contador=contador++;
            if(contador==8){
                contador=2;
            }
        }
      
    }
    
}
